name = "AcademicCV"
uuid = "6342e7ff-5917-4989-ac23-9add7aa15b9f"
authors = ["md-arif-shaikh"]
version = "0.1.0"

[deps]
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Mustache = "1.0"
YAML = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
